apiVersion: v1
kind: Pod
metadata:
  name: k8sdemo-pod
  labels:
    app: k8sdemo
spec:
  containers:
    - name: k8demo
      image: shai2311/webappdemo:1.0
      ports:
        - containerPort: 8080

